import type { FC } from 'react';
import Head from 'next/head';

import PageContainer from 'components/atoms/PageContainer/PageContainer';

export interface LandingPageProps {}

const Landing: FC<LandingPageProps> = () => {
  return (
    <PageContainer>
      <Head>
        <title>Igor Michalak</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Landing</h1>
    </PageContainer>
  );
};

export default Landing;
