import type { FC } from 'react';
import Head from 'next/head';
import Link from 'next/link';

export interface HomePageProps {}

const Home: FC<HomePageProps> = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Next.js app</h1>
      <Link href="/blog">Blog</Link>
    </>
  );
};

export default Home;
