import type { FC } from 'react';
import Head from 'next/head';

export interface AboutPageProps {}

const About: FC<AboutPageProps> = () => {
  return (
    <>
      <Head>
        <title>About Igor Michalak</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>About</h1>
    </>
  );
};

export default About;
